[workspace]
members = [
  "example"
]

[package]
name = "cdbc"
version = "0.1.0"
edition = "2021"
authors = ["zhuxiujia@qq.com"]


[features]
default = []
offline = ["serde"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
may = "0.3"
hashlink = "0.7.0"
thiserror = "1.0.30"
bytes = '1.0.0'
memchr = "2.3.4"
serde={version = "1.0.130" ,optional = true}
log = { version = "0.4.8", default-features = false }


crossbeam-queue = "0.3.1"
crossbeam-channel = "0.5.0"
crossbeam-utils = { version = "0.8.1", default-features = false }

either = "1.5.3"
bstr = { version = "0.2.14", default-features = false, features = ["std"], optional = true }
futures-core = { version = "0.3.5"}
futures-util = {version = "0.3",features = ["sink"]}
futures-intrusive = "0.4.0"
futures-channel="0.3"
sqlx-rt = {version = "0.5.9",features = ["runtime-tokio-native-tls"] }